* Original Brainstorm
** Medical Device
*** Purpose
To produce information to a user that will increase their quality
of life or provide valuable information to their health care provider
*** Possible Features
- Heart rate monitor
- Breath rate monitor
- Blood sugar monitor
- Blood pressure monitor
- Body temperature monitor
- Pulse oximeter/heart rate (MAX86141 + MAX32664)
- ECG (AD8232)
- Could also measure environment such as air quality (BME680) or noise
  levels
*** First Imagining
**** Form factor
Watch with large buttons (Final Fantasy Spirits Within Seiko Watch)
LCD (Not touch)
USB-C Port
Looks cool
**** Use cases in order of priority
1 - Data logging health stuff to find trends to better your life
2 - Telling you the time
3 - Have a generic watch OS (stopwatch, alarms, etc)
**** Features
Data export via USB and Bluetooth
All the sensors

** Exam Calculator
*** Purpose
A calculator that can be reprogrammed by an invigilator to provide
a student with only the features required for the exam they are
about to take.
*** Possible Features
 - General Calculations
 - Formula Sheets
 - Documentation
 - Fully featured scientific calculator with ability for university to
   provide and enforce profiles that mask out features not allowable for a
   specific exam
 - Ability for profiles to provide formulas and macros for specific exams
 - System for quick and easy provisioning of profiles at beginning of exam
   (possibly wireless)
 - Tamper resistance (ability to install keys for signing of profiles, some
   way to guarantee or verify that unmodified profile is in use during exam)
 - Ability to provide to exam markers a log of all calculations performed
   during exam
*** First imagining
Regular Calculator Form Factor
USB-C
Can load programs over USB
915MHz radio for provisioning
Visual provisioning indicator
Some form of firmware integrity check
** Drone finding drone
*** Purpose
A drone that can be deployed by authorities to detect and stop
unauthorized drones. Could be used to protect public events, or
no-fly zones.
*** Possible Features
- Deploy a net to stop other drones
- Detect other drones
- Identify drones as authorized or not

** Optical Wireless Communication System
*** Purpose
A communication system using visible (or near visible) spectrum. This could
be a "LiFi" type system that uses a smart light bulb to communicate with a
dedicated receiver. Another possible project would be an embedded device
which receives data from a smart phone through light from the phone's
screen. This would be a low cost alternative to using Bluetooth or NFC to
configure an embedded device.
*** Possible Features
- Smart light and client each connected to a computer via USB that allow a
  simple serial link (could demo with something like file transfer)
- Small embedded/IoT device of some kind provisioned with WiFi credentials
  via light from smartphone screen
- Smart light communicating with phone using screen and camera or ambient
  light sensor
*** First Imagining
Two devices receiver and a transmitter half duplex
Transmitter will be in a light bulb form factor
Receiver will be a speaker
