#+title: BioSense21

A university project by Morgan Smith, Samuel Dewan, Tadhg
McDonald-Jensen, and Jason Nyentap.
* Description
A wearable device that would contain a suite of sensors intended to
produce enough information to detect illness before symptoms occur.
* Feature List
** User Interface (do we need one?)
- Vibration Motor (for what?)
- A button (for what?)
- Speaker (for what?)
** Necessary Hardware
- Battery (Lithium Ion)
- Charging circuit
- Accelerometer IMU ($11.07) [[https://www.digikey.ca/en/products/detail/tdk-invensense/ICM-20948/6623535][ICM-20948]]
- Heart rate+oximeter
  ($11.77 [[https://www.digikey.ca/en/products/detail/maxim-integrated/MAX86150EFF/7392247][MAX86150EFF]])
  or
  ($3.64 [[https://www.digikey.ca/en/products/detail/osram-opto-semiconductors-inc/SFH-7050/6137020?s=N4IgTCBcDaIMoDEASACA7ABgKwZAXQF8g][SFH 7050]]) ($7.66 [[https://www.mouser.ca/ProductDetail/Maxim-Integrated/MAX32664GWEC%2bT?qs=%252B6g0mu59x7KPYz%252BeYnJYdg%3D%3D][MAX32664GWEC+T]]) ($10.13 [[https://www.mouser.ca/ProductDetail/Maxim-Integrated/MAX32664GTGC%2b?qs=vmHwEFxEFR%252B4L9bBONurNg%3D%3D][MAX86140ENP+T]])
- Body + Ambient temperature ($1.06 [[https://www.digikey.ca/en/products/detail/microchip-technology/TCN75AVUA713/739451][TCN75AVUA713]])
** Possible Sensors
- air quality ($18.39 [[https://www.digikey.ca/en/products/detail/bosch-sensortec/BME680/7401317][BME680]] includes temperature)
- noise levels (microphone)
- Breath rate sensor (how?) (Pulse oximetry?)
- Pulse oximeter/heart rate
- ECG (AD8232)
- UV exposure ($2.48 [[https://www.digikey.ca/en/products/detail/silicon-labs/SI1133-AA00-GMR/5725927][SI1133-AA00-GMR]])
** Need more research Sensors
- Blood sugar monitor
- Blood pressure monitor
* Similar Projects
** [[https://github.com/estherbm/Open-BioBand][Open-BioBand]]
The code is in Spanish (I think)
License: GPL-3
** [[https://www.pine64.org/pinetime/][PineTime]]
| Soc      | Sensors       | Battery |
|----------+---------------+---------|
| nRF52832 | Heart Rate    | 180 mAh |
|          | Accelerometer |         |

** [[https://www.kickstarter.com/projects/gfw/banglejs-the-hackable-smart-watch/description][Bangle.js]]
- This watch is specifically designed to run javascript, gross.

| Soc      | Sensors    | Battery |
|----------+------------+---------|
| nRF52832 | Heart Rate | 350 mAh |

** [[https://github.com/S-March/smarchWatch_PUBLIC][This random dude who made his own smartwatch]]
- More images here: [[https://imgur.com/a/FSBwD3g][link]]

| Soc     | Sensors       | Battery |
|---------+---------------+---------|
| DA14683 | Accelerometer |         |
* Available drivers and algorithms
https://www.owear.org/open-algorithms
* Studies on early sickness detection
** Currently happening
*** [[https://osher.ucsf.edu/research/current-research-studies/tempredict][TemPredict]]
Using the Oura Ring which is a wearable device that measures heart
rate, inter-beat interval and changes in dermal temperature and is
associated with a smartphone app.
*** [[https://innovations.stanford.edu/wearables][Stanford]]
For iOS users, we support: Fitbit devices, Garmin devices, Samsung Galaxy Watch, Apple Watch, Oura Ring.

For Android users, we support Fitbit devices.
*** [[https://detectstudy.org/][Detect Health Study]]
** Completed
*** [[https://doi.org/10.1016/S2589-7500(19)30222-5][Harnessing wearable device data to improve state-level real-time surveillance of influenza-like illness in the USA: a population-based study]]
References other studies that indicate that increased temperature due
to infection can cause a higher heart rate

Lack of sleep is correlated with an elevated heart rate.

Mentions they would have like to use detection of voice changes or
galvanic skin response to detect stress level to identify
non-infectious causes of elected heart rate.

Heart rate is higher when it's cold and lower when it's warm

Heart rate is higher when you're dehydrated
*** [[https://doi.org/10.1371/journal.pbio.2001402][Digital Health: Tracking Physiomes and Activity Using Wearable Biosensors Reveals Useful Health-Related Information]]
Core temperature decreases during sleep but skin temperature increases

Measurements taken during airline flights differ significantly from
normal measurements

Skin temperature increases from inflammation, and viral disease

Skin temperature increases a lot from Lyme disease

Heart rate increases noticeably when suffering
from Lyme disease or rhinovirus
